# Generated by Django 3.1.7 on 2021-04-21 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_auto_20210415_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
